extends Node

var HelenHouse = {
	"bits": 20, 
	"scene": "res://Scenes/EditorStages/HelenHouse.tscn", 
	"scene_ref_base": "SubViewport/HelenHouse/",
	"camera_count": 2,
	
	"ust_type": "Rockafire Explosion/3-Stage",
	
	"bit_mapping":
	{
		23: { "bot": "Helen", "movement": "Mouth", "flow_in": 3.0, "flow_out": 2.0 },
		24: { "bot": "Helen", "movement": "Left Ear", "flow_in": 3.5, "flow_out": 1.5 },
		25: { "bot": "Helen", "movement": "Right Ear", "flow_in": 3.5, "flow_out": 1.5 },
		26: { "bot": "Helen", "movement": "Left Eyelid", "flow_in": 1.5, "flow_out": 2.0 },
		27: { "bot": "Helen", "movement": "Right Eyelid", "flow_in": 1.5, "flow_out": 2.0 },
		28: { "bot": "Helen", "movement": "Eyes Left", "flow_in": 3.5, "flow_out": 1.5 },
		29: { "bot": "Helen", "movement": "Eyes Right", "flow_in": 3.5, "flow_out": 1.5 },
		30: { "bot": "Helen", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		31: { "bot": "Helen", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		32: { "bot": "Helen", "movement": "Head Up", "flow_in": 1.0, "flow_out": 1.0 },
		33: { "bot": "Helen", "movement": "Left Arm Up", "flow_in": 0.8, "flow_out": 0.6 },
		34: { "bot": "Helen", "movement": "Left Arm Twist", "flow_in": 0.8, "flow_out": 0.8 },
		35: { "bot": "Helen", "movement": "Left Elbow", "flow_in": 1.0, "flow_out": 1.0 },
		36: { "bot": "Helen", "movement": "Right Arm Up", "flow_in": 0.8, "flow_out": 0.6 },
		37: { "bot": "Helen", "movement": "Right Arm Twist", "flow_in": 0.8, "flow_out": 0.8 },
		38: { "bot": "Helen", "movement": "Right Elbow", "flow_in": 1.0, "flow_out": 1.0 },
		39: { "bot": "Helen", "movement": "Body Left", "flow_in": 0.7, "flow_out": 0.7 },
		40: { "bot": "Helen", "movement": "Body Right", "flow_in": 0.7, "flow_out": 0.7 },
		41: { "bot": "Helen", "movement": "Body Lean", "flow_in": 1.0, "flow_out": 0.8 },
		125: { "bot": "Spots", "movement": "Helen", "flow_in": "None", "flow_out": "None" },
	},
	
	"cosmetics": [ Cosmetics.HelenHouseHelen ],
	"cosmetic_defaults": [ 0, 0 ]
}

var ChuckEsCorner = {
	"bits": 16, 
	"scene": "res://Scenes/EditorStages/ChuckEsCorner.tscn", 
	"scene_ref_base": "SubViewport/ChuckEsCorner/",
	"camera_count": 3,
	
	"ust_type": "Cyberamics",
	
	"bit_mapping":
	{
		1: { "bot": "Chuck", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		2: { "bot": "Chuck", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		3: { "bot": "Chuck", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		4: { "bot": "Chuck", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		5: { "bot": "Chuck", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		6: { "bot": "Chuck", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		7: { "bot": "Chuck", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		8: { "bot": "Chuck", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		41: { "bot": "Warblettes", "movement": "Mouth", "flow_in": 4.0, "flow_out": 3.0 },
		44: { "bot": "Warblettes", "movement": "Body Rock", "flow_in": 1.0, "flow_out": 1.0 },
		50: { "bot": "Spots", "movement": "Chuck", "flow_in": "None", "flow_out": "None" },
		55: { "bot": "Floods", "movement": "Blue", "flow_in": "None", "flow_out": "None" },
		78: { "bot": "Spots", "movement": "Warblettes", "flow_in": "None", "flow_out": "None" },
		79: { "bot": "Color Spots", "movement": "Chuck", "flow_in": "None", "flow_out": "None" },
		82: { "bot": "Floods", "movement": "Red", "flow_in": "None", "flow_out": "None" },
		86: { "bot": "Floods", "movement": "Green", "flow_in": "None", "flow_out": "None" },
	},
	
	"cosmetics": [ Cosmetics.CyberChuck ],
	"cosmetic_defaults": [ 0, 1, 0, 0, 0, 0 ]
}

var BalconyStage = {
	"bits": 69, 
	"scene": "res://Scenes/EditorStages/Balcony.tscn", 
	"scene_ref_base": "SubViewport/Balcony/",
	"camera_count": 6,
	
	"ust_type": "Cyberamics",
	
	"bit_mapping":
	{
		1: { "bot": "Chuck", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		2: { "bot": "Chuck", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		3: { "bot": "Chuck", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		4: { "bot": "Chuck", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		5: { "bot": "Chuck", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		6: { "bot": "Chuck", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		7: { "bot": "Chuck", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		8: { "bot": "Chuck", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		9: { "bot": "Helen", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		10: { "bot": "Helen", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		11: { "bot": "Helen", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		12: { "bot": "Helen", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		13: { "bot": "Helen", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		14: { "bot": "Helen", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		15: { "bot": "Helen", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		16: { "bot": "Helen", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		17: { "bot": "Munch", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		18: { "bot": "Munch", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		19: { "bot": "Munch", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		20: { "bot": "Munch", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		21: { "bot": "Munch", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		22: { "bot": "Munch", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		23: { "bot": "Munch", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		24: { "bot": "Munch", "movement": "Left Arm", "flow_in": 2.0, "flow_out": 1.0 },
		25: { "bot": "Jasper", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		26: { "bot": "Jasper", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		27: { "bot": "Jasper", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		28: { "bot": "Jasper", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		29: { "bot": "Jasper", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		30: { "bot": "Jasper", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		31: { "bot": "Jasper", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		32: { "bot": "Jasper", "movement": "Strum", "flow_in": 2.0, "flow_out": 1.0 },
		33: { "bot": "Pasqually", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		34: { "bot": "Pasqually", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		35: { "bot": "Pasqually", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		36: { "bot": "Pasqually", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		37: { "bot": "Pasqually", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		38: { "bot": "Pasqually", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		39: { "bot": "Pasqually", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		40: { "bot": "Pasqually", "movement": "Left Arm", "flow_in": 2.0, "flow_out": 1.0 },
		41: { "bot": "Warblettes", "movement": "Mouth", "flow_in": 4.0, "flow_out": 3.0 },
		44: { "bot": "Warblettes", "movement": "Body Rock", "flow_in": 1.0, "flow_out": 1.0 },
		50: { "bot": "Spots", "movement": "Chuck", "flow_in": "None", "flow_out": "None" },
		51: { "bot": "Spots", "movement": "Helen", "flow_in": "None", "flow_out": "None" },
		52: { "bot": "Spots", "movement": "Munch", "flow_in": "None", "flow_out": "None" },
		53: { "bot": "Spots", "movement": "Jasper", "flow_in": "None", "flow_out": "None" },
		54: { "bot": "Spots", "movement": "Pasqually", "flow_in": "None", "flow_out": "None" },
		55: { "bot": "Backdrop", "movement": "C Blue", "flow_in": "None", "flow_out": "None" },
		65: { "bot": "Backdrop", "movement": "L Blue", "flow_in": "None", "flow_out": "None" },
		66: { "bot": "Valence", "movement": "R Center", "flow_in": "None", "flow_out": "None" },
		68: { "bot": "Backdrop", "movement": "L Red", "flow_in": "None", "flow_out": "None" },
		69: { "bot": "Valence", "movement": "R", "flow_in": "None", "flow_out": "None" },
		70: { "bot": "Backdrop", "movement": "L Amber", "flow_in": "None", "flow_out": "None" },
		71: { "bot": "Valence", "movement": "L Center", "flow_in": "None", "flow_out": "None" },
		72: { "bot": "Valence", "movement": "L", "flow_in": "None", "flow_out": "None" },
		73: { "bot": "Valence", "movement": "Center", "flow_in": "None", "flow_out": "None" },
		74: { "bot": "Color Spots", "movement": "Warblettes", "flow_in": "None", "flow_out": "None" },
		75: { "bot": "Color Spots", "movement": "Munch", "flow_in": "None", "flow_out": "None" },
		76: { "bot": "Color Spots", "movement": "Helen", "flow_in": "None", "flow_out": "None" },
		77: { "bot": "Color Spots", "movement": "Jasper", "flow_in": "None", "flow_out": "None" },
		78: { "bot": "Spots", "movement": "Warblettes", "flow_in": "None", "flow_out": "None" },
		79: { "bot": "Color Spots", "movement": "Chuck", "flow_in": "None", "flow_out": "None" },
		80: { "bot": "Color Spots", "movement": "Chuck 2", "flow_in": "None", "flow_out": "None" },
		81: { "bot": "Backdrop", "movement": "R Amber", "flow_in": "None", "flow_out": "None" },
		82: { "bot": "Backdrop", "movement": "C Red", "flow_in": "None", "flow_out": "None" },
		83: { "bot": "Backdrop", "movement": "R Blue", "flow_in": "None", "flow_out": "None" },
		84: { "bot": "Color Spots", "movement": "Pasqually", "flow_in": "None", "flow_out": "None" },
		85: { "bot": "Backdrop", "movement": "R Red", "flow_in": "None", "flow_out": "None" },
		86: { "bot": "Backdrop", "movement": "C Amber", "flow_in": "None", "flow_out": "None" },
	},
	
	"cosmetics": 
	[
		Cosmetics.CyberChuck,
		Cosmetics.CyberHelen,
		Cosmetics.CyberMunch,
		Cosmetics.CyberJasper,
		Cosmetics.CyberPasqually
	],
	"cosmetic_defaults": [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
}

var CStage = {
	"bits": 65, 
	"scene": "res://Scenes/EditorStages/CStage.tscn", 
	"scene_ref_base": "SubViewport/CStage/",
	"camera_count": 5,
	
	"ust_type": "Cyberamics",
	
	"bit_mapping":
	{
		1: { "bot": "Chuck", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		2: { "bot": "Chuck", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		3: { "bot": "Chuck", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		4: { "bot": "Chuck", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		5: { "bot": "Chuck", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		6: { "bot": "Chuck", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		7: { "bot": "Chuck", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		8: { "bot": "Chuck", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		9: { "bot": "Helen", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		10: { "bot": "Helen", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		11: { "bot": "Helen", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		12: { "bot": "Helen", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		13: { "bot": "Helen", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		14: { "bot": "Helen", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		15: { "bot": "Helen", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		16: { "bot": "Helen", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		17: { "bot": "Munch", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		18: { "bot": "Munch", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		19: { "bot": "Munch", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		20: { "bot": "Munch", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		21: { "bot": "Munch", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		22: { "bot": "Munch", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		23: { "bot": "Munch", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		24: { "bot": "Munch", "movement": "Left Arm", "flow_in": 2.0, "flow_out": 1.0 },
		25: { "bot": "Jasper", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		26: { "bot": "Jasper", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		27: { "bot": "Jasper", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		28: { "bot": "Jasper", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		29: { "bot": "Jasper", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		30: { "bot": "Jasper", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		31: { "bot": "Jasper", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		32: { "bot": "Jasper", "movement": "Strum", "flow_in": 2.0, "flow_out": 1.0 },
		33: { "bot": "Pasqually", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		34: { "bot": "Pasqually", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		35: { "bot": "Pasqually", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		36: { "bot": "Pasqually", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		37: { "bot": "Pasqually", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		38: { "bot": "Pasqually", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		39: { "bot": "Pasqually", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		40: { "bot": "Pasqually", "movement": "Left Arm", "flow_in": 2.0, "flow_out": 1.0 },
		50: { "bot": "Spots", "movement": "Chuck", "flow_in": "None", "flow_out": "None" },
		51: { "bot": "Spots", "movement": "Helen", "flow_in": "None", "flow_out": "None" },
		52: { "bot": "Spots", "movement": "Munch", "flow_in": "None", "flow_out": "None" },
		53: { "bot": "Spots", "movement": "Jasper", "flow_in": "None", "flow_out": "None" },
		54: { "bot": "Spots", "movement": "Pasqually", "flow_in": "None", "flow_out": "None" },
		55: { "bot": "Backdrop", "movement": "C Blue", "flow_in": "None", "flow_out": "None" },
		65: { "bot": "Backdrop", "movement": "L Blue", "flow_in": "None", "flow_out": "None" },
		66: { "bot": "Valence", "movement": "R Center", "flow_in": "None", "flow_out": "None" },
		68: { "bot": "Backdrop", "movement": "L Red", "flow_in": "None", "flow_out": "None" },
		69: { "bot": "Valence", "movement": "R", "flow_in": "None", "flow_out": "None" },
		70: { "bot": "Backdrop", "movement": "L Amber", "flow_in": "None", "flow_out": "None" },
		71: { "bot": "Valence", "movement": "L Center", "flow_in": "None", "flow_out": "None" },
		72: { "bot": "Valence", "movement": "L", "flow_in": "None", "flow_out": "None" },
		73: { "bot": "Valence", "movement": "Center", "flow_in": "None", "flow_out": "None" },
		75: { "bot": "Color Spots", "movement": "Munch", "flow_in": "None", "flow_out": "None" },
		76: { "bot": "Color Spots", "movement": "Helen", "flow_in": "None", "flow_out": "None" },
		77: { "bot": "Color Spots", "movement": "Jasper", "flow_in": "None", "flow_out": "None" },
		79: { "bot": "Color Spots", "movement": "Chuck", "flow_in": "None", "flow_out": "None" },
		80: { "bot": "Color Spots", "movement": "Chuck 2", "flow_in": "None", "flow_out": "None" },
		81: { "bot": "Backdrop", "movement": "R Amber", "flow_in": "None", "flow_out": "None" },
		82: { "bot": "Backdrop", "movement": "C Red", "flow_in": "None", "flow_out": "None" },
		83: { "bot": "Backdrop", "movement": "R Blue", "flow_in": "None", "flow_out": "None" },
		84: { "bot": "Color Spots", "movement": "Pasqually", "flow_in": "None", "flow_out": "None" },
		85: { "bot": "Backdrop", "movement": "R Red", "flow_in": "None", "flow_out": "None" },
		86: { "bot": "Backdrop", "movement": "C Amber", "flow_in": "None", "flow_out": "None" },
	},
	
	"cosmetics": 
	[
		Cosmetics.CyberChuck,
		Cosmetics.CyberHelen,
		Cosmetics.CyberMunch,
		Cosmetics.CyberJasper,
		Cosmetics.CyberPasqually
	],
	"cosmetic_defaults": [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
}

var ProtoRoadStage = {
	"bits": 41, 
	"scene": "res://Scenes/EditorStages/ProtoRoadStage.tscn", 
	"scene_ref_base": "SubViewport/ProtoRoadStage/",
	"camera_count": 6,
	
	"ust_type": "Cyberamics",
	
	"bit_mapping":
	{
		1: { "bot": "Chuck", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		2: { "bot": "Chuck", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		3: { "bot": "Chuck", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		4: { "bot": "Chuck", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		5: { "bot": "Chuck", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		6: { "bot": "Chuck", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		7: { "bot": "Chuck", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		8: { "bot": "Chuck", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		9: { "bot": "Helen", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		10: { "bot": "Helen", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		11: { "bot": "Helen", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		12: { "bot": "Helen", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		13: { "bot": "Helen", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		14: { "bot": "Helen", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		15: { "bot": "Helen", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		16: { "bot": "Helen", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		17: { "bot": "Munch", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		18: { "bot": "Munch", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		19: { "bot": "Munch", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		20: { "bot": "Munch", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		21: { "bot": "Munch", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		22: { "bot": "Munch", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		23: { "bot": "Munch", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		24: { "bot": "Munch", "movement": "Left Arm", "flow_in": 2.0, "flow_out": 1.0 },
		25: { "bot": "Jasper", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		26: { "bot": "Jasper", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		27: { "bot": "Jasper", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		28: { "bot": "Jasper", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		29: { "bot": "Jasper", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		30: { "bot": "Jasper", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		31: { "bot": "Jasper", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		32: { "bot": "Jasper", "movement": "Strum", "flow_in": 2.0, "flow_out": 1.0 },
		33: { "bot": "Pasqually", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		34: { "bot": "Pasqually", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		35: { "bot": "Pasqually", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		36: { "bot": "Pasqually", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		37: { "bot": "Pasqually", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		38: { "bot": "Pasqually", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		39: { "bot": "Pasqually", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		40: { "bot": "Pasqually", "movement": "Left Arm", "flow_in": 2.0, "flow_out": 1.0 },
		80: { "bot": "Special", "movement": "Neon Sign", "flow_in": "None", "flow_out": "None" },
	},
	
	"cosmetics": 
	[
		Cosmetics.CyberChuck,
		Cosmetics.CyberHelen,
		Cosmetics.CyberMunch,
		Cosmetics.CyberJasper,
		Cosmetics.CyberPasqually
	],
	"cosmetic_defaults": [ 1, 2, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 3, 2, 0, 1, 0, 0, 0, 0, 2 ]
}

var Cyber3Stage = {
	"bits": 40, 
	"scene": "res://Scenes/EditorStages/Cyber3Stage.tscn", 
	"scene_ref_base": "SubViewport/Cyber3Stage/",
	"camera_count": 4,
	
	"ust_type": "Cyberamics",
	
	"bit_mapping":
	{
		1: { "bot": "Chuck", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		2: { "bot": "Chuck", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		3: { "bot": "Chuck", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		4: { "bot": "Chuck", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		5: { "bot": "Chuck", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		6: { "bot": "Chuck", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		7: { "bot": "Chuck", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		8: { "bot": "Chuck", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		9: { "bot": "Helen", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		10: { "bot": "Helen", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		11: { "bot": "Helen", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		12: { "bot": "Helen", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		13: { "bot": "Helen", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		14: { "bot": "Helen", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		15: { "bot": "Helen", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		16: { "bot": "Helen", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		17: { "bot": "Munch", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		18: { "bot": "Munch", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		19: { "bot": "Munch", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		20: { "bot": "Munch", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		21: { "bot": "Munch", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		22: { "bot": "Munch", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		23: { "bot": "Munch", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		24: { "bot": "Munch", "movement": "Left Arm", "flow_in": 2.0, "flow_out": 1.0 },
		25: { "bot": "Jasper", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		26: { "bot": "Jasper", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		27: { "bot": "Jasper", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		28: { "bot": "Jasper", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		29: { "bot": "Jasper", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		30: { "bot": "Jasper", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		31: { "bot": "Jasper", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		32: { "bot": "Jasper", "movement": "Strum", "flow_in": 2.0, "flow_out": 1.0 },
		33: { "bot": "Pasqually", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		34: { "bot": "Pasqually", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		35: { "bot": "Pasqually", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		36: { "bot": "Pasqually", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		37: { "bot": "Pasqually", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		38: { "bot": "Pasqually", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		39: { "bot": "Pasqually", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		40: { "bot": "Pasqually", "movement": "Left Arm", "flow_in": 2.0, "flow_out": 1.0 },
	},
	
	"cosmetics": 
	[
		Cosmetics.CyberChuck,
		Cosmetics.CyberHelen,
		Cosmetics.CyberMunch,
		Cosmetics.CyberJasper,
		Cosmetics.CyberPasqually
	],
	"cosmetic_defaults": [ 4, 4, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 3 ]
}

var Cyber1Stage = {
	"bits": 69, 
	"scene": "res://Scenes/EditorStages/1Stage.tscn", 
	"scene_ref_base": "SubViewport/1Stage/",
	"camera_count": 5,
	
	"ust_type": "Cyberamics",
	
	"bit_mapping":
	{
		1: { "bot": "Chuck", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		2: { "bot": "Chuck", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		3: { "bot": "Chuck", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		4: { "bot": "Chuck", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		5: { "bot": "Chuck", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		6: { "bot": "Chuck", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		7: { "bot": "Chuck", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		8: { "bot": "Chuck", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		9: { "bot": "Helen", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		10: { "bot": "Helen", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		11: { "bot": "Helen", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		12: { "bot": "Helen", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		13: { "bot": "Helen", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		14: { "bot": "Helen", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		15: { "bot": "Helen", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		16: { "bot": "Helen", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		17: { "bot": "Munch", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		18: { "bot": "Munch", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		19: { "bot": "Munch", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		20: { "bot": "Munch", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		21: { "bot": "Munch", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		22: { "bot": "Munch", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		23: { "bot": "Munch", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		24: { "bot": "Munch", "movement": "Left Arm", "flow_in": 2.0, "flow_out": 1.0 },
		25: { "bot": "Jasper", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		26: { "bot": "Jasper", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		27: { "bot": "Jasper", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		28: { "bot": "Jasper", "movement": "Head Up", "flow_in": 2.0, "flow_out": 1.0 },
		29: { "bot": "Jasper", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		30: { "bot": "Jasper", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		31: { "bot": "Jasper", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		32: { "bot": "Jasper", "movement": "Strum", "flow_in": 2.0, "flow_out": 1.0 },
		33: { "bot": "Pasqually", "movement": "Mouth", "flow_in": 7.5, "flow_out": 6.0 },
		34: { "bot": "Pasqually", "movement": "Head Left", "flow_in": 1.5, "flow_out": 1.5 },
		35: { "bot": "Pasqually", "movement": "Head Right", "flow_in": 1.5, "flow_out": 1.5 },
		36: { "bot": "Pasqually", "movement": "Eyes Left", "flow_in": 4.0, "flow_out": 3.0 },
		37: { "bot": "Pasqually", "movement": "Eyes Right", "flow_in": 4.0, "flow_out": 3.0 },
		38: { "bot": "Pasqually", "movement": "Eyelids", "flow_in": 7.5, "flow_out": 5.0 },
		39: { "bot": "Pasqually", "movement": "Right Arm", "flow_in": 2.0, "flow_out": 1.0 },
		40: { "bot": "Pasqually", "movement": "Left Arm", "flow_in": 2.0, "flow_out": 1.0 },
		50: { "bot": "Spots", "movement": "Chuck", "flow_in": "None", "flow_out": "None" },
		51: { "bot": "Spots", "movement": "Helen", "flow_in": "None", "flow_out": "None" },
		52: { "bot": "Spots", "movement": "Munch", "flow_in": "None", "flow_out": "None" },
		53: { "bot": "Spots", "movement": "Jasper", "flow_in": "None", "flow_out": "None" },
		54: { "bot": "Spots", "movement": "Pasqually", "flow_in": "None", "flow_out": "None" },
		55: { "bot": "Spots", "movement": "Wink", "flow_in": "None", "flow_out": "None" },
		61: { "bot": "Curtain", "movement": "Up", "flow_in": 0.2, "flow_out": 0.2 },
		62: { "bot": "Curtain", "movement": "Down", "flow_in": 0.2, "flow_out": 0.2 },
		65: { "bot": "Floods", "movement": "CEC Red", "flow_in": "None", "flow_out": "None" },
		66: { "bot": "Floods", "movement": "CEC Amber", "flow_in": "None", "flow_out": "None" },
		67: { "bot": "Floods", "movement": "CEC Blue", "flow_in": "None", "flow_out": "None" },
		68: { "bot": "Floods", "movement": "Main Red", "flow_in": "None", "flow_out": "None" },
		69: { "bot": "Floods", "movement": "Main Amber", "flow_in": "None", "flow_out": "None" },
		70: { "bot": "Floods", "movement": "Main Blue", "flow_in": "None", "flow_out": "None" },
		71: { "bot": "Backdrop", "movement": "Red", "flow_in": "None", "flow_out": "None" },
		72: { "bot": "Backdrop", "movement": "Amber", "flow_in": "None", "flow_out": "None" },
		73: { "bot": "Backdrop", "movement": "Blue", "flow_in": "None", "flow_out": "None" },
		74: { "bot": "Organ", "movement": "Face Amber", "flow_in": "None", "flow_out": "None" },
		75: { "bot": "Organ", "movement": "Face Blue", "flow_in": "None", "flow_out": "None" },
		76: { "bot": "Organ", "movement": "Legs Outer", "flow_in": "None", "flow_out": "None" },
		77: { "bot": "Organ", "movement": "Legs Middle", "flow_in": "None", "flow_out": "None" },
		78: { "bot": "Organ", "movement": "Legs Inner", "flow_in": "None", "flow_out": "None" },
		79: { "bot": "Special", "movement": "CEC Sign", "flow_in": "None", "flow_out": "None" },
		80: { "bot": "Special", "movement": "CEC Rope Light", "flow_in": "None", "flow_out": "None" },
		82: { "bot": "Special", "movement": "Fiber Curtain", "flow_in": "None", "flow_out": "None" },
		83: { "bot": "Special", "movement": "Band Sign", "flow_in": "None", "flow_out": "None" },
		84: { "bot": "Special", "movement": "Drum Light", "flow_in": "None", "flow_out": "None" },
		85: { "bot": "Special", "movement": "Gobo Light", "flow_in": "None", "flow_out": "None" },
		86: { "bot": "Special Helicopter", "movement": "Light", "flow_in": 15.0, "flow_out": 6.0 },
	},
	
	"cosmetics": 
	[
		Cosmetics.CyberChuck,
		Cosmetics.CyberHelen,
		Cosmetics.CyberMunch,
		Cosmetics.CyberJasper,
		Cosmetics.CyberPasqually,
		Cosmetics.Valence,
		Cosmetics.Cyber1StageSpecial
	],
	"cosmetic_defaults": [ 1, 2, 1, 1, 1, 0, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 3, 0, 0, 0 ]
}

var stages_info = {
	"Helen House": HelenHouse,
	"Chuck E's Corner": ChuckEsCorner,
	"Balcony Stage": BalconyStage,
	"C-Stage": CStage,
	"Prototype Road Stage": ProtoRoadStage,
	"1-Stage": Cyber1Stage,
	"Cyberamic 3-Stage": Cyber3Stage,
}

var loaded_mods = { }
